### ISSUE TITLE
unable to track from card

### ISSUE THREAD

**Issue by sweetgman** [isabellaalstrom/lovelace-grocy-chores-card#33]
custom component: v1.1.1
chores card: v1.1.0

when i click on track in the chores card this is the error that pops up on screen.

![Grocy track error](https://user-images.githubusercontent.com/44832527/90301945-d802ff80-de70-11ea-8c3a-ba9a95e9f219.png)

from logs:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1345, in _execute_service
    handler.func(service_call)
  File "/config/custom_components/grocy/__init__.py", line 166, in handle_execute_chore
    grocy.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 515, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 546, in execute_chore
    localized_tracked_time = local_tz.localize(tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pytz/tzinfo.py", line 318, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

**Comment by isabellaalstrom** [comment]
Thank you. I see the same. Will try to fix right away!

**Comment by isabellaalstrom** [comment]
Card no longer sends datetime with the tracking call, so this should not be an issue anymore.
