### ISSUE TITLE
Grocy Error after pushing Track...

### ISSUE THREAD

**Issue by adtwomey** [isabellaalstrom/lovelace-grocy-chores-card#48]
Get this issues after pushing track.

Use Home Assistant Core 2021.4.4
Grocy custom component 3.0.5
Grocy Docker Version 3.0.1
Lovelace Grocy Chores Card 2.1.0
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 105, in async_call_grocy_service
    await async_execute_chore_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 207, in async_execute_chore_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 205, in wrapper
    coordinator.api.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 107, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 633, in execute_chore
    return self._do_post_request(f"chores/{chore_id}/execute", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 565, in _do_post_request
    raise GrocyError(resp)
pygrocy.errors.grocy_error.GrocyError: <Response [500]>
```

**Comment by isabellaalstrom** [comment]
This is actually an issue with the component, please open an issue [here](https://github.com/custom-components/grocy/issues/new?assignees=&labels=&template=bug_report.md&title=)
