### ISSUE TITLE
Failed to call service grocy/execute_chore. <Response [500]>

### ISSUE THREAD

**Issue by Galapagon** [isabellaalstrom/lovelace-grocy-chores-card#57]
When trying to mark chore as tracked using this card I'm getting a response 500 error. I'm guessing it's my own fault but I'm not sure why.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/grocy/services.py:205
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: June 2, 2021, 7:44:43 PM (14 occurrences)
Last logged: 5:16:07 PM

[140046089280624] <Response [500]>
[140046424331744] <Response [500]>
[140046033914848] <Response [500]>
[140046041939488] <Response [500]>
[140046034013488] <Response [500]>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 105, in async_call_grocy_service
    await async_execute_chore_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 207, in async_execute_chore_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 205, in wrapper
    coordinator.api.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 107, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 633, in execute_chore
    return self._do_post_request(f"chores/{chore_id}/execute", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 565, in _do_post_request
    raise GrocyError(resp)
pygrocy.errors.grocy_error.GrocyError: <Response [500]>

**Comment by isabellaalstrom** [comment]
Have you followed these instructions? https://github.com/isabellaalstrom/lovelace-grocy-chores-card#-how-to-get-the-correct-user-id

**Comment by Galapagon** [comment]
Dof! I appologize, I thought that that was if I wanted to use the non-default User key. My API is user 1 but I was trying to use User_id: 2 

That's currently not possible because of the bug, is that right? I misunderstood before.

**Comment by isabellaalstrom** [comment]
Yeah that's right!
