### ISSUE TITLE
Adding a task fails

### ISSUE THREAD

**Issue by munterkalmsteiner** [isabellaalstrom/lovelace-grocy-chores-card#58]
When trying to add a task from the card, I get the following error message:
Failed to call service grocy/add_generic. 'str' object has no attribute 'value'

Running grocy 0.15.0 and HA core-2021.7.4.

**Comment by isabellaalstrom** [comment]
I need more information since everything works for me. Have it worked before?

**Comment by munterkalmsteiner** [comment]
It never worked as I just installed the card. I'm running now HA core 2021.8.8 (supervised), grocy 3.1.0 and grocy HA addon 0.15.0. I tried both with the webclient and the android app, same error.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/grocy/services.py:239
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21 August 2021, 22:10:58 (3 occurrences)
Last logged: 11:55:28

[140318331066784] 'str' object has no attribute 'value'
[140318210719600] 'str' object has no attribute 'value'
[140318293852112] 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 111, in async_call_grocy_service
    await async_add_generic_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 241, in async_add_generic_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 239, in wrapper
    coordinator.api.add_generic(entity_type, data)
  File "/usr/local/lib/python3.9/site-packages/pygrocy/grocy.py", line 216, in add_generic
    return self._api_client.add_generic(entity_type.value, data)
AttributeError: 'str' object has no attribute 'value'

**Comment by munterkalmsteiner** [comment]
Updating the grocy custom component to v3.2.0 solved the issue for me.
