### ISSUE TITLE
Error when tracking Chore "object has no attribute 'localize'"

### ISSUE THREAD

**Issue by Leotendo** [isabellaalstrom/lovelace-grocy-chores-card#60]
Howdy, I am getting an error when clicking the "Track" button on the chore card. 

- The issue started this week, I believe shortly after I upgraded from core-2021.8.2 to core-2021.8.7. 
- Issue persisted when upgrading to core-2021.8.8
- Issue no longer exists when restoring a snapshot to core-2021.8.2 

Please let me know if there is anything else you need from me to help investigate the issue. 

"Failed to call service grocy/execute_chore. 'zoneinfo.ZoneInfo' object has no attribute 'localize'"
![image](https://user-images.githubusercontent.com/24616792/130141832-8077d893-4284-4452-897d-3226323fa9be.png)

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/grocy/services.py:205
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:19:37 PM (3 occurrences)
Last logged: 5:20:38 PM

[548255661744] 'zoneinfo.ZoneInfo' object has no attribute 'localize'
[548195155776] 'zoneinfo.ZoneInfo' object has no attribute 'localize'
[547967789232] 'zoneinfo.ZoneInfo' object has no attribute 'localize'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 105, in async_call_grocy_service
    await async_execute_chore_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 207, in async_execute_chore_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 205, in wrapper
    coordinator.api.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.9/site-packages/pygrocy/grocy.py", line 107, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.9/site-packages/pygrocy/grocy_api_client.py", line 626, in execute_chore
    localized_tracked_time = localize_datetime(tracked_time)
  File "/usr/local/lib/python3.9/site-packages/pygrocy/utils.py", line 47, in localize_datetime
    return local_tz.localize(timestamp).astimezone(pytz.utc)
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'

**Comment by isabellaalstrom** [comment]
I tried to remove the date to remedy this, but it seems to be a problem from pygrocy. https://github.com/SebRut/pygrocy/issues/175

I will maybe try to add a workaround fix in the meantime.

**Comment by ajobbins** [comment]
This still seems to be an issue. Just started running Grocy v3.3.1 and v3.2 of this card on HA 2022.8.3 (so latest version of everything) and getting this exact same error when trying to track a chore using this card.
